name: release

# run only on tags
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # needed to write releases

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
      - name: Set output
        id: macos_sdk
        run: echo "path=$(xcrun --show-sdk-path)" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          version: latest
          args: release --clean
        env:
          SDK_PATH: ${{ steps.macos_sdk.outputs.path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
